spring.application.name=demo
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
jwt.secretKey=${jwt_secret_key}

spring.security.oauth2.client.registration.google.client-id=1234
spring.security.oauth2.client.registration.google.client-secret==1234

spring.security.oauth2.client.registration.github.client-id=Ov23liJtI8ZDZybNqqny
spring.security.oauth2.client.registration.github.client-secret=461a330b6b7a17efe238cc68009acebcb9f2887e